{{- if .Values.ingress.enabled -}}
{{- $fullName := include "wordpress.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "wordpress.name" . }}
    chart: {{ template "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  backend:
    serviceName: {{ $fullName }}
    servicePort: http
{{- end }}
